name: Python Package using Conda

on:
  push:
    branches:
      - main

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.10 and Conda
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Configure Conda
      run: |
        python -m pip install --upgrade pip
        conda init bash
    - name: Install dependencies
      run: |
        conda create --name myenv python=3.10
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        source $CONDA/etc/profile.d/conda.sh
        conda activate myenv
        conda install pytest
        pytest

